# Generated by Django 4.1.7 on 2023-02-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groceries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('quantity_in_packets', models.SmallIntegerField(blank=True, null=True)),
                ('quantity_in_weight', models.CharField(blank=True, max_length=10, null=True)),
                ('quantity_in_volume', models.CharField(blank=True, max_length=10, null=True)),
                ('price_per_packet', models.SmallIntegerField(blank=True, null=True)),
                ('price_per_kg', models.SmallIntegerField(blank=True, null=True)),
                ('price_per_litre', models.SmallIntegerField(blank=True, null=True)),
                ('total_sale_in_stock', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
