# Generated by Django 4.1.7 on 2023-02-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groceries',
            old_name='name',
            new_name='product_name',
        ),
    ]
