# Generated by Django 4.1.7 on 2023-02-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_makeup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeup',
            name='left_quantity',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='makeup',
            name='price_per_pack',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
