# Generated by Django 4.1.7 on 2023-02-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_makeup_left_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile_phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=20)),
                ('processor_name', models.CharField(max_length=20)),
                ('storage_capacity', models.CharField(max_length=10)),
                ('price', models.SmallIntegerField(default=0)),
                ('monthly_sale', models.SmallIntegerField(default=0)),
                ('left_stock', models.SmallIntegerField(default=0)),
                ('ordered_new_stock', models.CharField(max_length=10)),
            ],
        ),
    ]
