# Generated by Django 4.1.7 on 2023-02-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_mobile_phones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groceries',
            name='price_per_kg',
        ),
        migrations.RemoveField(
            model_name='groceries',
            name='price_per_litre',
        ),
        migrations.RemoveField(
            model_name='groceries',
            name='price_per_packet',
        ),
        migrations.AddField(
            model_name='groceries',
            name='price',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
