# Generated by Django 4.1.7 on 2023-02-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_groceries_price_per_kg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='makeup',
            old_name='price_per_pack',
            new_name='price',
        ),
        migrations.AddField(
            model_name='groceries',
            name='description',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='makeup',
            name='description',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mobile_phones',
            name='description',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='groceries',
            name='price',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
